#### 1.原始訊息
##### 收到日期：20260813
##### 完成日期：20260817
##### 花費時間：4 Hr
需求：以加權指數自 2000/1/1 起日資料，當日收盤價若向上穿越過季線（60日），則買入；反之，則賣出。請統計出以下幾項資料：

- ⬤ 總損益、交易次數、勝率、平均賺賠比、最大連續虧損
- ⬤ 最後持有部位資訊（進場日、多空、價位）
- ⬤ （進階）統計所有出場交易之損益、持有時間

P.S：
- 1）先以金融市場習慣說法為主，查了若仍不懂請勇於提問。利用每次機會知道對方的邏輯
- 2）本策略一旦進場後，非多即空，不會空手
- 3）可能是題組，請考量日後調整彈性
- 4）不限制使用工具（個人偏好EXCEL、GOOGLE SPREADSHEET）

#### 2.策略及定義假設
- **基本設定**
  - 標的：台灣加權指數（TAIEX / Y9999）
  - 資料頻率：日資料
  - 回測起始日：2000/01/01
  - 季線：60 日簡單移動平均線（SMA60）

- **交易規則**
  - 做多
    - 昨日收盤價 ≤ 昨日 SMA60
    - 今日收盤價 > 今日 SMA60
    - 視為**向上穿越季線**，建立多頭部位（Long）
  - 做空
    - 昨日收盤價 ≥ 昨日 SMA60
    - 今日收盤價 < 今日 SMA60
    - 視為**向下穿越季線**，建立空頭部位（Short）
  - 部位規則
    - 策略開始持有部位後，維持**非多即空**
    - 不存在空手狀態
    - 出現反向訊號時：
      1. 將原有部位平倉
      2. 同時建立反向部位

- **成交假設**
  - 訊號以**當日收盤價**判斷
  - 假設以**訊號當日收盤價成交**

- **損益定義**
  - 損益先以**加權指數點數**表示
  - 暫不考慮：
    - 初始本金
    - 每點價值
    - 交易成本
    - 手續費
    - 稅費
    - 滑價
      - 原本預期成交的價格，和實際真正成交的價格之間的差距。
      - 例如你看到加權指數在 20,000 點出現買進訊號，理論上希望用 20,000 點成交，但實際下單後可能成交在 20,005 點，這多出來的 5 點就是滑價。
      - 滑價常見原因包括市場快速波動、流動性不足、買賣價差，以及從訊號產生到訂單真正進市場之間的時間差。

- **交易定義**
  - 一筆完整交易定義為：
    - **進場 → 持有 → 出場**
  - 反手時：
    - 原部位完成一筆交易
    - 同時開始下一筆反向交易
  - 尚未出場的最後一筆部位視為**未平倉部位（Open Position）**

- **持有時間**
  - 持有時間以**交易日（Trading Days）**計算
  - 定義：
    - 今日收盤進場，下一個交易日收盤出場，持有時間為 1 個交易日
  - 不使用日曆日計算，因此週末及休市日不額外計入持有時間

- **績效指標**
  - 總損益
    - 所有已完成交易之損益點數加總
  - 交易次數
    - 完成「進場 → 出場」的交易筆數
    - 未平倉的最後部位不列入已完成交易次數
  - 勝率
    - 獲利交易次數占全部已完成交易次數的比例
  - 平均賺賠比
    - 平均獲利交易的獲利點數，相對於平均虧損交易虧損點數絕對值的比例
  - 最大連續虧損
    - 歷史交易紀錄中，連續出現虧損交易的最大筆數

- **最後持有部位**
  - 紀錄回測資料截止日仍持有之部位：
    - 進場日
    - 多空方向（Long / Short）
    - 進場價位

- **出場交易明細**
  - 每筆已完成交易至少紀錄：
    - 進場日
    - 出場日
    - 多空方向
    - 進場價
    - 出場價
    - 損益點數
    - 持有交易日數

- **第一筆部位如何建立**
  - 等待回測起始日後第一次穿越訊號再進場

##### 3.程式內容

DB 連線測試

In [29]:
import pandas as pd
import os
from dotenv import load_dotenv
import psycopg

load_dotenv("../../.env")

try:
    conn = psycopg.connect(
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT"),
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        connect_timeout=5
    )

    with conn.cursor() as cur:
        cur.execute("""
            SELECT
                current_database(),
                current_user,
                version();
        """)

        database, user, version = cur.fetchone()

    print("PostgreSQL 連線成功")
    print("Database :", database)
    print("User     :", user)
    print("Version  :", version)

except psycopg.Error as e:
    print("PostgreSQL 連線失敗")
    print(e)

finally:
    if 'conn' in locals():
        conn.close()

PostgreSQL 連線成功
Database : market_data
User     : market_data_user
Version  : PostgreSQL 18.4 (Debian 18.4-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit

In [30]:
if 'conn' not in globals() or conn.closed:
    conn = psycopg.connect(
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT"),
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        connect_timeout=5
    )

print("PostgreSQL 連線狀態：", "已連線" if not conn.closed else "已關閉")

PostgreSQL 連線狀態： 已連線

In [31]:
conn.rollback()

In [32]:
import pandas as pd

sql = """
SELECT
    md.trade_date,
    md.close_price
    
FROM instrument i
JOIN market_daily md
    ON md.instrument_id = i.id
WHERE i.code = %s
ORDER BY md.trade_date;
"""

with conn.cursor() as cur:
    cur.execute(sql, ("Y9999",))

    rows = cur.fetchall()
    columns = [desc.name for desc in cur.description]

df = pd.DataFrame(rows, columns=columns)
df["close_price"] = pd.to_numeric(df["close_price"])
df["trade_date"] = pd.to_datetime(df["trade_date"])

In [33]:
df.head()

  trade_date  close_price
0 1999-06-01      7397.62
1 1999-06-02      7488.03
2 1999-06-03      7572.91
3 1999-06-04      7590.44
4 1999-06-05      7639.30

In [34]:
df[["trade_date", "close_price"]]

     trade_date  close_price
0    1999-06-01      7397.62
1    1999-06-02      7488.03
2    1999-06-03      7572.91
3    1999-06-04      7590.44
4    1999-06-05      7639.30
5    1999-06-07      7802.69
6    1999-06-08      7892.13
7    1999-06-09      7957.71
8    1999-06-10      7996.76
9    1999-06-11      7979.40
10   1999-06-14      7973.58
11   1999-06-15      7960.00
12   1999-06-16      8059.02
13   1999-06-17      8274.36
14   1999-06-21      8413.48
15   1999-06-22      8608.91
16   1999-06-23      8492.32
17   1999-06-24      8589.31
18   1999-06-25      8265.96
19   1999-06-28      8281.45
20   1999-06-29      8514.27
21   1999-06-30      8467.37
22   1999-07-02      8572.09
23   1999-07-03      8563.55
24   1999-07-05      8593.35
25   1999-07-06      8454.49
26   1999-07-07      8470.07
27   1999-07-08      8592.43
28   1999-07-09      8550.27
29   1999-07-12      8463.90
30   1999-07-13      8204.50
31   1999-07-14      7888.66
32   1999-07-15      7918.04
33   1999-07-16      7411.58
34   1999-07-17      7366.23
35   1999-07-19      7386.89
36   1999-07-20      7806.85
37   1999-07-21      7786.65
38   1999-07-22      7678.67
39   1999-07-23      7724.52
40   1999-07-26      7595.71
41   1999-07-27      7367.97
42   1999-07-28      7484.50
43   1999-07-29      7359.37
44   1999-07-30      7413.11
45   1999-07-31      7326.75
46   1999-08-02      7195.94
47   1999-08-03      7175.19
48   1999-08-04      7110.80
49   1999-08-05      6959.73
50   1999-08-06      6823.52
51   1999-08-07      7049.74
52   1999-08-09      7028.01
53   1999-08-10      7269.60
54   1999-08-11      7228.68
55   1999-08-12      7330.24
56   1999-08-13      7626.05
57   1999-08-16      8018.47
58   1999-08-17      8083.43
59   1999-08-18      7993.71
60   1999-08-19      7964.67
61   1999-08-20      8117.42
62   1999-08-21      8153.57
63   1999-08-23      8119.98
64   1999-08-24      7984.39
65   1999-08-25      8127.09
66   1999-08-26      8097.57
67   1999-08-27      8053.97
68   1999-08-30      8071.36
69   1999-08-31      8157.73
70   1999-09-01      8273.33
71   1999-09-02      8226.15
72   1999-09-03      8073.97
73   1999-09-04      8065.11
74   1999-09-06      8130.28
75   1999-09-07      7945.76
76   1999-09-08      7973.30
77   1999-09-09      8025.02
78   1999-09-10      8161.46
79   1999-09-13      8178.69
80   1999-09-14      8092.02
81   1999-09-15      7971.04
82   1999-09-16      7968.90
83   1999-09-17      7916.92
84   1999-09-18      8016.93
85   1999-09-20      7972.14
86   1999-09-27      7759.93
87   1999-09-28      7577.85
88   1999-09-29      7615.45
89   1999-09-30      7598.79
90   1999-10-01      7694.99
91   1999-10-02      7659.55
92   1999-10-04      7685.48
93   1999-10-05      7557.01
94   1999-10-06      7501.63
95   1999-10-07      7612.00
96   1999-10-08      7552.98
97   1999-10-11      7607.11
98   1999-10-12      7835.37
99   1999-10-13      7836.94
100  1999-10-14      7879.91
101  1999-10-15      7819.09
102  1999-10-16      7829.39
103  1999-10-18      7745.26
104  1999-10-19      7692.96
105  1999-10-20      7666.64
106  1999-10-21      7654.90
107  1999-10-22      7559.63
108  1999-10-25      7680.87
109  1999-10-26      7700.29
110  1999-10-27      7701.22
111  1999-10-28      7681.85
112  1999-10-29      7706.67
113  1999-10-30      7854.85
114  1999-11-01      7814.89
115  1999-11-02      7721.59
116  1999-11-03      7580.09
117  1999-11-04      7469.23
118  1999-11-05      7488.26
119  1999-11-06      7376.56
120  1999-11-08      7401.49
121  1999-11-09      7362.69
122  1999-11-10      7401.81
123  1999-11-11      7532.22
124  1999-11-15      7545.03
125  1999-11-16      7606.20
126  1999-11-17      7645.78
127  1999-11-18      7718.06
128  1999-11-19      7770.81
129  1999-11-20      7900.34
130  1999-11-22      8052.31
131  1999-11-23      8046.19
132  1999-11-24      7921.85
133  1999-11-25      7904.53
134  1999-11-26      7595.44
135  1999-11-29      7823.90
136  1999-11-30      7720.87
137  1999-12-01      7766.20
138  1999-12-02      7806.26
139  1999-12-03      7933.17
140  1999-12-04      7964.49
141  1999-12-06      7894.46
142  1999-12-07      7827.05
143  1999-12-08      7811.02
144  1999-12-09      7738.84
145  1999-12-10      7733.77
146  1999-12-13      7883.61
147  1999-12-14      7850.14
148  1999-12-15      7859.89
149  1999-12-16      7739.76
150  1999-12-17      7723.22
151  1999-12-18      7797.87
152  1999-12-20      7782.94
153  1999-12-21      7934.26
154  1999-12-22      8002.76
155  1999-12-23      8083.49
156  1999-12-24      8219.45
157  1999-12-27      8415.07
158  1999-12-28      8448.84
159  2000-01-04      8756.55
160  2000-01-05      8849.87
161  2000-01-06      8922.03
162  2000-01-07      8845.47
163  2000-01-10      9102.60
164  2000-01-11      8927.03
165  2000-01-12      9144.65
166  2000-01-13      9107.19
167  2000-01-14      9023.24
168  2000-01-15      9191.37
169  2000-01-17      9315.43
170  2000-01-18      9250.19
171  2000-01-19      9151.44
172  2000-01-20      9136.95
173  2000-01-21      9255.94
174  2000-01-24      9387.07
175  2000-01-25      9372.37
176  2000-01-26      9581.96
177  2000-01-27      9628.98
178  2000-01-28      9696.91
179  2000-01-29      9636.38
180  2000-01-31      9744.89
181  2000-02-01      9856.39
182  2000-02-09     10008.88
183  2000-02-10     10057.67
184  2000-02-11     10128.67
185  2000-02-14      9971.45
186  2000-02-15      9957.74
187  2000-02-16     10064.49
188  2000-02-17     10202.20
189  2000-02-18     10096.38
190  2000-02-19     10161.05
191  2000-02-21      9912.67
192  2000-02-22      9731.93
193  2000-02-23      9642.26
194  2000-02-24      9599.17
195  2000-02-25      9432.49
196  2000-02-29      9435.94
197  2000-03-01      9689.10
198  2000-03-02      9543.82
199  2000-03-03      9588.03
200  2000-03-04      9517.97
201  2000-03-06      9367.91
202  2000-03-07      9380.07
203  2000-03-08      9389.49
204  2000-03-09      9587.27
205  2000-03-10      9429.60
206  2000-03-13      8811.95
207  2000-03-14      8835.58
208  2000-03-15      8640.03
209  2000-03-16      8682.76
210  2000-03-17      8763.27
211  2000-03-20      8536.05
212  2000-03-21      9004.48
213  2000-03-22      9069.39
214  2000-03-23      9533.87
215  2000-03-24      9482.64
216  2000-03-27      9807.57
217  2000-03-28      9856.60
218  2000-03-29      9805.69
219  2000-03-30      9931.94
220  2000-03-31      9854.95
221  2000-04-01     10050.43
222  2000-04-05     10186.17
223  2000-04-06      9969.28
224  2000-04-07      9921.03
225  2000-04-08      9934.57
226  2000-04-10     10127.48
227  2000-04-11     10068.05
228  2000-04-12      9911.39
229  2000-04-13      9662.60
230  2000-04-14      9374.61
231  2000-04-15      8866.80
232  2000-04-17      8993.68
233  2000-04-18      9307.03
234  2000-04-19      9104.40
235  2000-04-20      9109.05
236  2000-04-21      9120.48
237  2000-04-24      8808.09
238  2000-04-25      8921.12
239  2000-04-26      8535.96
240  2000-04-27      8541.95
241  2000-04-28      8824.36
242  2000-04-29      8777.35
243  2000-05-02      8638.75
244  2000-05-03      8420.00
245  2000-05-04      8425.38
246  2000-05-05      8698.53
247  2000-05-06      8657.13
248  2000-05-08      8616.18
249  2000-05-09      8635.84
250  2000-05-10      8559.87
251  2000-05-11      8349.91
252  2000-05-12      8560.44
253  2000-05-15      8465.02
254  2000-05-16      8727.82
255  2000-05-17      9085.74
256  2000-05-18      9087.21
257  2000-05-19      9119.77
258  2000-05-20      8820.35
259  2000-05-22      8807.57
260  2000-05-23      8671.01
261  2000-05-24      8500.41
262  2000-05-25      8438.10
263  2000-05-26      8559.46
264  2000-05-29      8588.25
265  2000-05-30      8764.42
266  2000-05-31      8939.52
267  2000-06-01      8842.63
268  2000-06-02      8883.45
269  2000-06-03      8935.64
270  2000-06-05      8958.21
271  2000-06-07      9115.47
272  2000-06-08      9067.88
273  2000-06-09      9036.66
274  2000-06-12      8955.44
275  2000-06-13      8891.09
276  2000-06-14      8935.23
277  2000-06-15      8844.97
278  2000-06-16      8832.15
279  2000-06-17      8770.80
280  2000-06-19      8751.10
281  2000-06-20      8690.66
282  2000-06-21      8637.60
283  2000-06-22      8771.77
284  2000-06-23      8684.93
285  2000-06-26      8529.56
286  2000-06-27      8424.17
287  2000-06-28      8365.63
288  2000-06-29      8120.89
289  2000-06-30      8265.09
290  2000-07-03      8297.77
291  2000-07-04      8052.54
292  2000-07-05      8421.74
293  2000-07-06      8289.39
294  2000-07-07      8173.08
295  2000-07-10      8154.67
296  2000-07-11      8158.63
297  2000-07-12      8059.75
298  2000-07-13      8267.66
299  2000-07-14      8497.13
300  2000-07-15      8518.13
301  2000-07-17      8585.52
302  2000-07-18      8368.78
303  2000-07-19      8411.88
304  2000-07-20      8219.53
305  2000-07-21      8167.37
306  2000-07-24      8064.20
307  2000-07-25      7900.39
308  2000-07-26      7961.54
309  2000-07-27      7956.28
310  2000-07-28      8122.11
311  2000-07-29      8143.93
312  2000-07-31      8114.92
313  2000-08-01      7984.65
314  2000-08-02      7916.85
315  2000-08-03      7844.93
316  2000-08-04      7925.20
317  2000-08-05      7841.43
318  2000-08-07      7715.99
319  2000-08-08      7797.78
320  2000-08-09      8048.14
321  2000-08-10      8024.69
322  2000-08-11      7974.65
323  2000-08-14      7848.87
324  2000-08-15      7845.69
325  2000-08-16      8003.53
326  2000-08-17      8143.25
327  2000-08-18      8176.82
328  2000-08-19      8209.07
329  2000-08-21      8257.88
330  2000-08-22      8118.05
331  2000-08-24      8098.84
332  2000-08-25      8026.32
333  2000-08-28      7845.87
334  2000-08-29      7817.49
335  2000-08-30      7543.96
336  2000-08-31      7616.98
337  2000-09-01      7420.06
338  2000-09-02      7707.59
339  2000-09-04      7803.02
340  2000-09-05      7785.62
341  2000-09-06      7610.78
342  2000-09-07      7430.93
343  2000-09-08      7367.99
344  2000-09-11      7335.20
345  2000-09-13      7391.66
346  2000-09-14      7152.29
347  2000-09-15      7155.45
348  2000-09-16      7053.29
349  2000-09-18      6910.14
350  2000-09-19      6734.90
351  2000-09-20      6880.09
352  2000-09-21      6920.90
353  2000-09-22      6612.09
354  2000-09-25      6677.46
355  2000-09-26      6749.03
356  2000-09-27      6717.04
357  2000-09-28      6564.87
358  2000-09-29      6432.36
359  2000-09-30      6185.14
360  2000-10-02      6024.07
361  2000-10-03      6143.44
362  2000-10-04      5997.92
363  2000-10-05      6029.65
364  2000-10-06      6353.67
365  2000-10-07      6352.03
366  2000-10-09      6209.42
367  2000-10-11      6040.55
368  2000-10-12      5805.01
369  2000-10-13      5876.11
370  2000-10-16      5630.95
371  2000-10-17      5702.36
372  2000-10-18      5432.23
373  2000-10-19      5081.28
374  2000-10-20      5404.78
375  2000-10-21      5599.74
376  2000-10-23      5680.95
377  2000-10-24      5918.63
378  2000-10-25      6023.78
379  2000-10-26      5941.85
380  2000-10-27      5805.17
381  2000-10-30      5659.08
382  2000-10-31      5544.18
383  2000-11-01      5425.02
384  2000-11-02      5626.08
385  2000-11-03      5796.08
386  2000-11-04      5677.30
387  2000-11-06      5657.48
388  2000-11-07      5877.77
389  2000-11-08      6067.94
390  2000-11-09      6089.55
391  2000-11-10      6088.74
392  2000-11-13      5793.52
393  2000-11-14      5772.51
394  2000-11-15      5737.02
395  2000-11-16      5454.13
396  2000-11-17      5351.36
397  2000-11-18      5167.35
398  2000-11-20      4845.21
399  2000-11-21      5103.00
400  2000-11-22      5130.61
401  2000-11-23      5146.92
402  2000-11-24      5419.99
403  2000-11-27      5433.78
404  2000-11-28      5362.26
405  2000-11-29      5319.46
406  2000-11-30      5256.93
407  2000-12-01      5342.06
408  2000-12-02      5277.35
409  2000-12-04      5174.02
410  2000-12-05      5199.20
411  2000-12-06      5170.62
412  2000-12-07      5212.73
413  2000-12-08      5252.83
414  2000-12-11      5284.41
415  2000-12-12      5380.09
416  2000-12-13      5384.36
417  2000-12-14      5320.16
418  2000-12-15      5224.74
419  2000-12-16      5134.10
420  2000-12-18      5055.20
421  2000-12-19      5040.25
422  2000-12-20      4947.89
423  2000-12-21      4817.22
424  2000-12-22      4811.22
425  2000-12-26      4721.36
426  2000-12-27      4614.63
427  2000-12-28      4797.14
428  2000-12-29      4743.94
429  2000-12-30      4739.09
430  2001-01-02      4935.28
431  2001-01-03      4894.79
432  2001-01-04      5136.13
433  2001-01-05      5295.53
434  2001-01-08      5188.51
435  2001-01-09      5376.12
436  2001-01-10      5436.78
437  2001-01-11      5369.24
438  2001-01-12      5339.40
439  2001-01-15      5379.66
440  2001-01-16      5662.94
441  2001-01-17      5769.95
442  2001-01-18      5847.91
443  2001-01-29      5680.06
444  2001-01-30      5792.50
445  2001-01-31      5936.20
446  2001-02-01      5897.93
447  2001-02-02      6049.26
448  2001-02-05      5932.42
449  2001-02-06      5849.06
450  2001-02-07      5693.58
451  2001-02-08      5758.60
452  2001-02-09      5809.84
453  2001-02-12      5847.07
454  2001-02-13      6027.49
455  2001-02-14      5887.68
456  2001-02-15      6104.24
457  2001-02-16      6045.67
458  2001-02-19      5937.30
459  2001-02-20      5971.29
460  2001-02-21      5949.96
461  2001-02-22      5759.04
462  2001-02-23      5726.93
463  2001-02-26      5716.02
464  2001-02-27      5674.69
465  2001-03-01      5499.86
466  2001-03-02      5499.54
467  2001-03-05      5609.74
468  2001-03-06      5635.06
469  2001-03-07      5777.13
470  2001-03-08      5711.02
471  2001-03-09      5680.43
472  2001-03-12      5582.67
473  2001-03-13      5610.40
474  2001-03-14      5658.21
475  2001-03-15      5742.74
476  2001-03-16      5783.93
477  2001-03-19      5641.89
478  2001-03-20      5642.70
479  2001-03-21      5623.42
480  2001-03-22      5730.95
481  2001-03-23      5800.55
482  2001-03-26      5896.32
483  2001-03-27      5884.33
484  2001-03-28      5819.39
485  2001-03-29      5833.88
486  2001-03-30      5797.92
487  2001-04-02      5607.73
488  2001-04-03      5446.82
489  2001-04-04      5405.85
490  2001-04-06      5515.13
491  2001-04-09      5401.83
492  2001-04-10      5353.50
493  2001-04-11      5467.75
494  2001-04-12      5533.22
495  2001-04-13      5495.47
496  2001-04-16      5432.28
497  2001-04-17      5431.95
498  2001-04-18      5508.61
499  2001-04-19      5608.50
500  2001-04-20      5596.63
501  2001-04-23      5597.70
502  2001-04-24      5589.34
503  2001-04-25      5516.20
504  2001-04-26      5518.73
505  2001-04-27      5416.67
506  2001-04-30      5381.67
507  2001-05-02      5304.24
508  2001-05-03      5405.54
509  2001-05-04      5244.05
510  2001-05-07      5229.93
511  2001-05-08      5176.71
512  2001-05-09      5232.64
513  2001-05-10      5122.17
514  2001-05-11      5232.72
515  2001-05-14      5176.45
516  2001-05-15      5158.79
517  2001-05-16      5082.02
518  2001-05-17      5143.44
519  2001-05-18      5111.67
520  2001-05-21      4958.61
521  2001-05-22      4991.48
522  2001-05-23      5209.97
523  2001-05-24      5226.79
524  2001-05-25      5170.08
525  2001-05-28      5079.72
526  2001-05-29      5095.26
527  2001-05-30      5057.07
528  2001-05-31      5048.86
529  2001-06-01      5013.96
530  2001-06-04      4985.11
531  2001-06-05      5065.06
532  2001-06-06      5220.44
533  2001-06-07      5153.35
534  2001-06-08      5226.28
535  2001-06-11      5271.30
536  2001-06-12      5266.24
537  2001-06-13      5209.71
538  2001-06-14      5119.19
539  2001-06-15      5158.63
540  2001-06-18      5070.52
541  2001-06-19      5039.98
542  2001-06-20      5029.64
543  2001-06-21      4984.88
544  2001-06-22      4904.34
545  2001-06-26      4785.12
546  2001-06-27      4825.28
547  2001-06-28      4768.55
548  2001-06-29      4883.43
549  2001-07-02      4886.86
550  2001-07-03      4843.82
551  2001-07-04      4739.16
552  2001-07-05      4709.20
553  2001-07-06      4707.01
554  2001-07-09      4657.30
555  2001-07-10      4616.71
556  2001-07-11      4548.29
557  2001-07-12      4633.54
558  2001-07-13      4485.68
559  2001-07-16      4368.69
560  2001-07-17      4371.99
561  2001-07-18      4219.89
562  2001-07-19      4190.78
563  2001-07-20      4220.33
564  2001-07-23      4151.93
565  2001-07-24      4040.77
566  2001-07-25      4136.39
567  2001-07-26      4300.41
568  2001-07-27      4320.59
569  2001-07-31      4352.98
570  2001-08-01      4354.52
571  2001-08-02      4490.19
572  2001-08-03      4530.68
573  2001-08-06      4470.73
574  2001-08-07      4404.00
575  2001-08-08      4514.10
576  2001-08-09      4448.52
577  2001-08-10      4476.91
578  2001-08-13      4520.76
579  2001-08-14      4589.60
580  2001-08-15      4623.11
581  2001-08-16      4687.33
582  2001-08-17      4638.36
583  2001-08-20      4550.36
584  2001-08-21      4562.73
585  2001-08-22      4487.52
586  2001-08-23      4459.76
587  2001-08-24      4310.32
588  2001-08-27      4384.55
589  2001-08-28      4368.38
590  2001-08-29      4508.69
591  2001-08-30      4503.86
592  2001-08-31      4509.44
593  2001-09-03      4454.77
594  2001-09-04      4493.53
595  2001-09-05      4424.91
596  2001-09-06      4338.26
597  2001-09-07      4302.16
598  2001-09-10      4289.10
599  2001-09-11      4176.93
600  2001-09-13      3952.49
601  2001-09-14      3774.62
602  2001-09-19      3781.17
603  2001-09-20      3698.84
604  2001-09-21      3591.85
605  2001-09-24      3533.51
606  2001-09-25      3493.78
607  2001-09-26      3625.53
608  2001-09-27      3567.63
609  2001-09-28      3636.94
610  2001-10-02      3492.12
611  2001-10-03      3446.26
612  2001-10-04      3493.66
613  2001-10-05      3585.46
614  2001-10-08      3520.35
615  2001-10-09      3618.93
616  2001-10-11      3789.93
617  2001-10-12      3801.50
618  2001-10-15      3712.82
619  2001-10-16      3794.86
620  2001-10-17      3817.13
621  2001-10-18      3811.20
622  2001-10-19      3845.62
623  2001-10-22      3900.62
624  2001-10-23      3874.42
625  2001-10-24      3986.67
626  2001-10-25      4012.20
627  2001-10-26      4043.57
628  2001-10-29      4065.10
629  2001-10-30      3915.61
630  2001-10-31      3903.49
631  2001-11-01      3929.69
632  2001-11-02      3998.48
633  2001-11-05      4080.51
634  2001-11-06      4082.92
635  2001-11-07      4158.15
636  2001-11-08      4135.03
637  2001-11-09      4123.78
638  2001-11-12      4172.63
639  2001-11-13      4136.54
640  2001-11-14      4277.70
641  2001-11-15      4403.59
642  2001-11-16      4446.62
643  2001-11-19      4548.63
644  2001-11-20      4455.80
645  2001-11-21      4533.37
646  2001-11-22      4450.02
647  2001-11-23      4519.08
648  2001-11-26      4608.32
649  2001-11-27      4580.33
650  2001-11-28      4447.58
651  2001-11-29      4465.83
652  2001-11-30      4441.12
653  2001-12-03      4646.61
654  2001-12-04      4766.43
655  2001-12-05      4924.56
656  2001-12-06      5208.86
657  2001-12-07      5333.93
658  2001-12-10      5321.28
659  2001-12-11      5273.97
660  2001-12-12      5539.31
661  2001-12-13      5407.54
662  2001-12-14      5486.73
663  2001-12-17      5456.15
664  2001-12-18      5329.19
665  2001-12-19      5221.96
666  2001-12-20      5309.10
667  2001-12-21      5109.24
668  2001-12-24      5164.73
669  2001-12-25      5372.81
670  2001-12-26      5392.43
671  2001-12-27      5332.98
672  2001-12-28      5398.28
673  2001-12-31      5551.24
674  2002-01-02      5600.05
675  2002-01-03      5526.32
676  2002-01-04      5638.53
677  2002-01-07      5834.89
678  2002-01-08      5810.08
679  2002-01-09      5865.54
680  2002-01-10      5871.28
681  2002-01-11      5687.59
682  2002-01-14      5611.86
683  2002-01-15      5592.74
684  2002-01-16      5488.33
685  2002-01-17      5501.13
686  2002-01-18      5522.80
687  2002-01-21      5798.05

In [35]:
# df.describe()
# df.head()
df.tail()
# df.info()
# df.shape

     trade_date  close_price
6728 2026-08-06     44396.70
6729 2026-08-07     44225.91
6730 2026-08-10     44928.76
6731 2026-08-11     45120.72
6732 2026-08-12     45518.07

In [36]:
df.iloc[2]
df["test"] = 1
df.loc[0, "test"] = 10000
df.loc[61]

trade_date     1999-08-20 00:00:00
close_price                8117.42
test                             1
Name: 61, dtype: object

sma

In [37]:
def get_sma(index, dateCount = 60):
    sumValue = 0
    for i in range (dateCount):
        currIndex = index - i
        currCloseValue = df.loc[currIndex,"close_price"]
        sumValue += currCloseValue
    return sumValue/dateCount

sma = get_sma(100)
smaa = df["close_price"].rolling(60).mean().iloc[100]

In [38]:
df["sma60"] = df["close_price"].rolling(60).mean()

signal : Enum
- "Long"
- "Short"
- "-"

In [39]:

def get_signal(index):
    currValue = df.loc[index, "close_price"]
    currSma = df.loc[index, "sma60"]

    yestValue = df.loc[index - 1, "close_price"]
    yestSma = df.loc[index - 1, "sma60"]

    if currValue > currSma and yestValue <= yestSma:
        # print(index, "L")
        return "Long"

    elif currValue < currSma and yestValue >= yestSma:
        # print(index, "S")
        return "Short"
    else:
        return "-"

df["signal"] = "-"
for index in  range(60, len(df)):
    
    df.loc[index, "signal"] = get_signal(index)

In [40]:
df.tail()

     trade_date  close_price  test         sma60 signal
6728 2026-08-06     44396.70     1  44231.234833      -
6729 2026-08-07     44225.91     1  44278.758333  Short
6730 2026-08-10     44928.76     1  44331.708500   Long
6731 2026-08-11     45120.72     1  44397.514500      -
6732 2026-08-12     45518.07     1  44474.618667      -

In [41]:
signal_df = df.loc[
    (df["signal"] != "-") & (df["trade_date"] >= pd.Timestamp("2000-01-01")),
    ["trade_date", "close_price", "sma60", "signal"]
].copy()
signal_df = signal_df.reset_index(drop=True)
signal_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   trade_date   334 non-null    datetime64[s]
 1   close_price  334 non-null    float64
 2   sma60        334 non-null    float64
 3   signal       334 non-null    str
dtypes: datetime64[s](1), float64(2), str(1)
memory usage: 10.6 KB

交易次數

In [42]:
print("交易次數",len(signal_df))

交易次數 334

In [43]:
def get_profit(index):
    currValue = signal_df.loc[index, "close_price"]
    yestValue = signal_df.loc[index - 1, "close_price"]
    isLong = signal_df.loc[index -1, "signal"] == "Long"
    
    if(isLong):
        return currValue - yestValue
    else: 
        return yestValue - currValue
    
def get_hold_day(index):
    currDay = signal_df.loc[index, "trade_date"]
    yestDay = signal_df.loc[index - 1, "trade_date"]
    hold_day = (currDay - yestDay).days
    return hold_day



for index in  range(1, len(signal_df)):
    signal_df.loc[index - 1, "profit"] = get_profit(index)
    signal_df.loc[index -1, "hold_day"] = get_hold_day(index)

In [44]:
signal_df.tail()

    trade_date  close_price         sma60 signal  profit  hold_day
329 2026-07-21     44232.87  43709.963000   Long -578.03       3.0
330 2026-07-24     43654.84  43964.307500  Short -956.76      12.0
331 2026-08-05     44611.60  44189.595167   Long -385.69       2.0
332 2026-08-07     44225.91  44278.758333  Short -702.85       3.0
333 2026-08-10     44928.76  44331.708500   Long     NaN       NaN

In [45]:
sum_profit = 0
win_count = 0
loss_count = 0

win_profit_sum = 0
loss_profit_sum = 0


loss_continue_max = 0
curr_loss_continue_count = 0

def set_loss_coutinue(is_profit_win):
    global curr_loss_continue_count
    global loss_continue_max
    if(is_profit_win):
        
        if(curr_loss_continue_count > loss_continue_max):
            loss_continue_max = curr_loss_continue_count
        curr_loss_continue_count = 0
    else:
        curr_loss_continue_count = curr_loss_continue_count + 1
    

for index in range(0, len(signal_df) - 1):
    sum_profit = sum_profit+signal_df.loc[index, "profit"]
    profit = signal_df.loc[index,"profit"]
    
    if(profit > 0):
        win_count = win_count + 1
        win_profit_sum = win_profit_sum + profit
        set_loss_coutinue(True)
        
    else:
        set_loss_coutinue(False)
        loss_count = loss_count + 1
        loss_profit_sum = loss_profit_sum + profit

total_count = win_count + loss_count
if total_count > 0:
    win_rate = win_count / total_count
else:
    win_rate = 0
    
print("sum_profit:",f"{sum_profit:.2f}")
print("win_ratef:",f"{win_rate*100:.2f}%")

win_profit_mean = win_profit_sum / win_count
loss_profit_mean = loss_profit_sum / loss_count

print ("win_profit_mean:", f"{win_profit_mean:.2f}")
print ("loss_profit_mean:", f"{loss_profit_mean:.2f}")
profit_ratio = abs(win_profit_mean) / abs(loss_profit_mean)
print ("profit_ratio:", f"{profit_ratio:.2f}")
print ("loss_continue_max:",loss_continue_max)

sum_profit: 32879.93
win_ratef: 23.42%
win_profit_mean: 921.20
loss_profit_mean: -152.84
profit_ratio: 6.03
loss_continue_max: 24

In [46]:
signal_df.iloc[len(signal_df)-1]

trade_date     2026-08-10 00:00:00
close_price               44928.76
sma60                   44331.7085
signal                        Long
profit                         NaN
hold_day                       NaN
Name: 333, dtype: object

In [47]:
print("-" * 10, "統計資訊", "-" * 10)
print("總損益",f"{sum_profit:.2f}")
print("交易次數",len(signal_df))
print("勝率",f"{win_rate*100:.2f}%")
print("平均賺賠比", f"{profit_ratio:.2f}")
print("最大連續虧損", loss_continue_max)
print("-" * 10, "最後持有部位資訊", "-" * 10)

print("進場日", signal_df.loc[len(signal_df)-1, "trade_date"])
print("多空", signal_df.loc[len(signal_df)-1, "signal"])
print("價位", signal_df.loc[len(signal_df)-1, "close_price"])

print("-" * 10, "統計所有出場交易之損益、持有時間", "-" * 10)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

print(signal_df)
print("-" * 10, "其它資訊", "-" * 10)
print("最高持有日",signal_df["hold_day"].max())
print("單次最高獲利",f"{signal_df["profit"].max():.2f}")
print("單次最高虧損",f"{signal_df["profit"].min():.2f}")

---------- 統計資訊 ----------
總損益 32879.93
交易次數 334
勝率 23.42%
平均賺賠比 6.03
最大連續虧損 24
---------- 最後持有部位資訊 ----------
進場日 2026-08-10 00:00:00
多空 Long
價位 44928.76
---------- 統計所有出場交易之損益、持有時間 ----------
    trade_date  close_price         sma60 signal   profit  hold_day
0   2000-03-13      8811.95   9190.846500  Short  -721.92      10.0
1   2000-03-23      9533.87   9330.423000   Long  -159.26      22.0
2   2000-04-14      9374.61   9602.798500  Short   259.14      54.0
3   2000-06-07      9115.47   9088.918167   Long   -47.59       1.0
4   2000-06-08      9067.88   9089.974833  Short  3691.76     215.0
5   2001-01-09      5376.12   5344.077000   Long   231.61      83.0
6   2001-04-02      5607.73   5653.865167  Short  1527.22     217.0
7   2001-11-05      4080.51   4068.742000   Long  1787.32     178.0
8   2002-05-02      5867.83   6049.507333  Short  1277.95     174.0
9   2002-10-23      4589.88   4538.422333   Long   -91.15       7.0
10  2002-10-30      4498.73   4511.314333  Short   -80.41       1.0
11  2002-10-31      4579.14   4511.427500   Long   -78.59       1.0
12  2002-11-01      4500.55   4507.757833  Short   -83.13       3.0
13  2002-11-04      4583.68   4505.815333   Long   -99.25      51.0
14  2002-12-25      4484.43   4527.518833  Short   -82.94       1.0
15  2002-12-26      4567.37   4534.112333   Long  -109.62       4.0
16  2002-12-30      4457.75   4548.467333  Short  -168.57       4.0
17  2003-01-03      4626.32   4577.929167   Long    17.55      38.0
18  2003-02-10      4643.87   4730.782167  Short    34.55      65.0
19  2003-04-16      4609.32   4591.349333   Long   -42.66       1.0
20  2003-04-17      4566.66   4584.253333  Short   -91.64       1.0
21  2003-04-18      4658.30   4578.263333   Long  -102.20       4.0
22  2003-04-22      4556.10   4567.482500  Short    -8.83       1.0
23  2003-04-23      4564.93   4561.047500   Long  -189.99       1.0
24  2003-04-24      4374.94   4551.532000  Short   -90.63      32.0
25  2003-05-26      4465.57   4400.141500   Long  1368.67     178.0
26  2003-11-20      5834.24   5847.082833  Short   -26.94       5.0
27  2003-11-25      5861.18   5860.173500   Long    -0.57       1.0
28  2003-11-26      5860.61   5862.987167  Short    -9.56       5.0
29  2003-12-01      5870.17   5869.116333   Long   -23.02       7.0
30  2003-12-08      5847.15   5888.260333  Short   -77.09       7.0
31  2003-12-15      5924.24   5900.497833   Long   -37.01       1.0
32  2003-12-16      5887.23   5904.022500  Short  -154.33      17.0
33  2004-01-02      6041.56   5930.267167   Long   318.36      80.0
34  2004-03-22      6359.92   6422.920000  Short  -114.19       7.0
35  2004-03-29      6474.11   6456.228167   Long   100.64      30.0
36  2004-04-28      6574.75   6645.792833  Short   951.89     114.0
37  2004-08-20      5622.86   5605.720667   Long    40.02      67.0
38  2004-10-26      5662.88   5742.637167  Short  -199.97       8.0
39  2004-11-03      5862.85   5777.616500   Long   -24.43      19.0
40  2004-11-22      5838.42   5878.207500  Short   -72.89       2.0
41  2004-11-24      5911.31   5881.136833   Long   -56.07       1.0
42  2004-11-25      5855.24   5882.631833  Short   -38.03       8.0
43  2004-12-03      5893.27   5883.090833   Long   -14.38      10.0
44  2004-12-13      5878.89   5885.461167  Short   -30.76       1.0
45  2004-12-14      5909.65   5886.982167   Long   -30.57      29.0
46  2005-01-12      5879.08   5911.896000  Short   -66.19       5.0
47  2005-01-17      5945.27   5917.370667   Long   -49.92       2.0
48  2005-01-19      5895.35   5925.955167  Short   -98.88      12.0
49  2005-01-31      5994.23   5933.187000   Long    38.24      45.0
50  2005-03-17      6032.47   6035.415167  Short   -11.48       1.0
51  2005-03-18      6043.95   6036.104667   Long   -25.16       4.0
52  2005-03-22      6018.79   6036.924667  Short   -47.12       3.0
53  2005-03-25      6065.91   6038.776167   Long  -104.67       4.0
54  2005-03-29      5961.24   6038.657667  Short   -30.31      59.0
55  2005-05-27      5991.55   5965.754333   Long   253.58      80.0
56  2005-08-15      6245.13   6246.156167  Short   169.87      88.0
57  2005-11-11      6075.26   5990.631833   Long   399.43     104.0
58  2006-02-23      6474.69   6489.860000  Short   -63.53       1.0
59  2006-02-24      6538.22   6496.965500   Long   -44.07      11.0
60  2006-03-07      6494.15   6536.261833  Short  -119.82      24.0
61  2006-03-31      6613.97   6567.408167   Long   232.98      60.0
62  2006-05-30      6846.95   6852.802667  Short   -25.89       2.0
63  2006-06-01      6872.84   6857.753667   Long  -157.57       4.0
64  2006-06-05      6715.27   6869.773500  Short   103.37      70.0
65  2006-08-14      6611.90   6563.958667   Long  -105.98       7.0
66  2006-08-21      6505.92   6545.155500  Short   -84.28       1.0
67  2006-08-22      6590.20   6540.344167   Long  -145.44       6.0
68  2006-08-28      6444.76   6518.398333  Short  -142.36       2.0
69  2006-08-30      6587.12   6513.798667   Long  1091.55     183.0
70  2007-03-01      7678.67   7727.322500  Short   -58.79      18.0
71  2007-03-19      7737.46   7733.381333   Long    -1.26       1.0
72  2007-03-20      7736.20   7737.644500  Short   -20.83       1.0
73  2007-03-21      7757.03   7741.281333   Long   836.01     147.0
74  2007-08-15      8593.04   8884.331833  Short  -389.12      16.0
75  2007-08-31      8982.16   8955.963333   Long   -59.18       4.0
76  2007-09-04      8922.98   8977.019167  Short   -94.10       2.0
77  2007-09-06      9017.08   8997.257167   Long   -79.50       4.0
78  2007-09-10      8937.58   9012.778833  Short   -94.05       4.0
79  2007-09-14      9031.63   9024.664167   Long  -131.72       3.0
80  2007-09-17      8899.91   9024.009500  Short  -205.37       4.0
81  2007-09-21      9105.28   9030.874333   Long  -167.70      48.0
82  2007-11-08      8937.58   9180.298500  Short   828.87     106.0
83  2008-02-22      8108.71   8106.111500   Long  -103.25      24.0
84  2008-03-17      8005.46   8060.419333  Short  -173.89       2.0
85  2008-03-19      8179.35   8059.271667   Long   528.48      68.0
86  2008-05-26      8707.83   8740.800333  Short   -70.56       1.0
87  2008-05-27      8778.39   8746.894167   Long  -112.66       1.0
88  2008-05-28      8665.73   8753.608500  Short  3967.42     222.0
89  2009-01-05      4698.31   4596.765000   Long  -162.52       3.0
90  2009-01-08      4535.79   4573.601333  Short    64.54      29.0
91  2009-02-06      4471.25   4460.428833   Long   -34.31      14.0
92  2009-02-20      4436.94   4457.967500  Short   -40.84       3.0
93  2009-02-23      4477.78   4464.431667   Long   -47.60       1.0
94  2009-02-24      4430.18   4468.749667  Short   -63.56       1.0
95  2009-02-25      4493.74   4474.303000   Long   -67.91       5.0
96  2009-03-02      4425.83   4482.794667  Short  -115.59       2.0
97  2009-03-04      4541.42   4482.758667   Long  1603.11     106.0
98  2009-06-18      6144.53   6159.051833  Short   -86.62       1.0
99  2009-06-19      6231.15   6173.798000   Long   -33.68       4.0
100 2009-06-23      6197.47   6203.155000  Short  -182.61       1.0
101 2009-06-24      6380.08   6222.722167   Long   274.72      58.0
102 2009-08-21      6654.80   6717.085500  Short  -183.45       3.0
103 2009-08-24      6838.25   6715.154667   Long  -147.50       3.0
104 2009-08-27      6690.75   6708.339500  Short  -119.11       1.0
105 2009-08-28      6809.86   6709.052167   Long   681.05      91.0
106 2009-11-27      7490.91   7532.720500  Short   -91.30       3.0
107 2009-11-30      7582.21   7538.680833   Long    16.60      57.0
108 2010-01-26      7598.81   7863.860000  Short  -249.03      50.0
109 2010-03-17      7847.84   7816.541000   Long   -35.97       6.0
110 2010-03-23      7811.87   7822.825667  Short   -26.23       2.0
111 2010-03-25      7838.10   7823.118000   Long  -141.20      41.0
112 2010-05-05      7696.90   7800.488167  Short    88.05      64.0
113 2010-07-08      7608.85   7571.069833   Long     7.43      54.0
114 2010-08-31      7616.28   7670.082500  Short  -104.54       2.0
115 2010-09-02      7720.82   7689.506000   Long   889.04     162.0
116 2011-02-11      8609.86   8749.497833  Short  -233.98       7.0
117 2011-02-18      8843.84   8786.834167   Long  -170.17       4.0
118 2011-02-22      8673.67   8800.698500  Short  -178.31      43.0
119 2011-04-06      8851.98   8759.614500   Long  -119.39       6.0
120 2011-04-12      8732.59   8752.411500  Short   -47.61       1.0
121 2011-04-13      8780.20   8750.694667   Long   -62.08       2.0
122 2011-04-15      8718.12   8749.365500  Short   -95.16       5.0
123 2011-04-20      8813.28   8737.605000   Long   -65.77      33.0
124 2011-05-23      8747.51   8758.177500  Short   -40.89       3.0
125 2011-05-26      8788.40   8768.208667   Long   -75.45      18.0
126 2011-06-13      8712.95   8823.067667  Short   -81.29      43.0
127 2011-07-26      8794.24   8782.007500   Long   -27.04       2.0
128 2011-07-28      8767.20   8776.861833  Short  1231.38      90.0
129 2011-10-26      7535.82   7484.594167   Long  -227.14      15.0
130 2011-11-10      7308.68   7420.889167  Short  -216.97       4.0
131 2011-11-14      7525.65   7413.159333   Long  -138.13       2.0
132 2011-11-16      7387.52   7416.876500  Short   208.65      55.0
133 2012-01-10      7178.87   7168.521500   Long   -75.25       6.0
134 2012-01-16      7103.62   7157.479000  Short  -117.46       1.0
135 2012-01-17      7221.08   7152.976833   Long   418.74      79.0
136 2012-04-05      7639.82   7759.017333  Short   294.66      88.0
137 2012-07-02      7345.16   7343.921167   Long   -35.20       7.0
138 2012-07-09      7309.96   7319.885667  Short    39.47      22.0
139 2012-07-31      7270.49   7197.322833   Long   181.23      72.0
140 2012-10-11      7451.72   7453.891333  Short   -19.30       5.0
141 2012-10-16      7471.02   7469.969000   Long    -6.62       1.0
142 2012-10-17      7464.40   7477.230167  Short    34.20      41.0
143 2012-11-27      7430.20   7425.024000   Long   367.83     113.0
144 2013-03-20      7798.03   7810.622167  Short   -58.09       5.0
145 2013-03-25      7856.12   7819.150333   Long  -103.33      14.0
146 2013-04-08      7752.79   7856.380500  Short  -105.19       3.0
147 2013-04-11      7857.98   7855.001667   Long   -36.35       1.0
148 2013-04-12      7821.63   7856.110667  Short  -109.17       7.0
149 2013-04-19      7930.80   7859.123000   Long    20.86      55.0
150 2013-06-13      7951.66   8055.029500  Short  -227.88      28.0
151 2013-07-11      8179.54   8088.694833   Long  -117.51       8.0
152 2013-07-19      8062.03   8118.412500  Short  -152.62       4.0
153 2013-07-23      8214.65   8123.017333   Long  -130.15       6.0
154 2013-07-29      8084.50   8126.462833  Short   -79.05       1.0
155 2013-07-30      8163.55   8126.371167   Long   -55.61       1.0
156 2013-07-31      8107.94   8125.452500  Short   -30.69       5.0
157 2013-08-05      8138.63   8116.477333   Long   -99.72       1.0
158 2013-08-06      8038.91   8112.987167  Short    17.02      24.0
159 2013-08-30      8021.89   8002.158833   Long   160.67      73.0
160 2013-11-11      8182.56   8210.336833  Short   -77.65       8.0
161 2013-11-19      8260.21   8240.843667   Long   -55.75       1.0
162 2013-11-20      8204.46   8246.001833  Short   -91.42       7.0
163 2013-11-27      8295.88   8268.066000   Long   -31.40      70.0
164 2014-02-05      8264.48   8402.984667  Short  -166.08       6.0
165 2014-02-11      8430.56   8410.708000   Long   710.88     175.0
166 2014-08-05      9141.44   9250.864667  Short  -238.66      17.0
167 2014-08-22      9380.10   9310.212333   Long   -22.49      19.0
168 2014-09-10      9357.61   9364.458333  Short   278.74      71.0
169 2014-11-20      9078.87   9029.075000   Long  -127.96      26.0
170 2014-12-16      8950.91   8958.955333  Short   -48.61       3.0
171 2014-12-19      8999.52   8950.814167   Long   611.31     146.0
172 2015-05-14      9610.83   9638.610167  Short  -105.94       5.0
173 2015-05-19      9716.77   9649.126333   Long  -138.21       2.0
174 2015-05-21      9578.56   9654.215333  Short   -90.85       5.0
175 2015-05-26      9669.41   9655.798000   Long   -43.72       6.0
176 2015-06-01      9625.69   9660.501000  Short  1231.59     127.0
177 2015-10-06      8394.10   8357.239000   Long   -64.60      38.0
178 2015-11-13      8329.50   8340.392667  Short   -89.92       4.0
179 2015-11-17      8419.42   8351.445500   Long   -78.95       1.0
180 2015-11-18      8340.47   8360.671333  Short  -136.73       1.0
181 2015-11-19      8477.20   8378.452333   Long   -77.06       5.0
182 2015-11-24      8400.14   8414.044667  Short   -84.76       2.0
183 2015-11-26      8484.90   8425.326833   Long   -86.50       1.0
184 2015-11-27      8398.40   8431.674167  Short   -64.90       4.0
185 2015-12-01      8463.30   8442.552000   Long    -7.24       2.0
186 2015-12-03      8456.06   8457.990333  Short   243.99      75.0
187 2016-02-16      8212.07   8154.395833   Long   261.80      72.0
188 2016-04-28      8473.87   8485.638000  Short   -62.00      32.0
189 2016-05-30      8535.87   8499.787333   Long   -77.00      28.0
190 2016-06-27      8458.87   8466.061333  Short   -46.64       1.0
191 2016-06-28      8505.51   8462.202500   Long   441.55      76.0
192 2016-09-12      8947.06   8964.526333  Short  -205.82       7.0
193 2016-09-19      9152.88   8979.830167   Long   -13.84      44.0
194 2016-11-02      9139.04   9172.555000  Short   -50.80       5.0
195 2016-11-07      9189.84   9171.351667   Long  -246.64       2.0
196 2016-11-09      8943.20   9168.491333  Short  -235.03      14.0
197 2016-11-23      9178.23   9159.675500   Long   -26.12       1.0
198 2016-11-24      9152.11   9160.015333  Short   -70.13       4.0
199 2016-11-28      9222.24   9162.691667   Long   -61.58       7.0
200 2016-12-05      9160.66   9174.645667  Short   -90.11       1.0
201 2016-12-06      9250.77   9174.507333   Long   -46.51      15.0
202 2016-12-21      9204.26   9210.701667  Short   -49.24       9.0
203 2016-12-30      9253.50   9199.274333   Long   386.44     110.0
204 2017-04-19      9639.94   9704.357333  Short   -77.47       2.0
205 2017-04-21      9717.41   9715.673000   Long     0.54       3.0
206 2017-04-24      9717.95   9721.730000  Short  -123.76       1.0
207 2017-04-25      9841.71   9730.059000   Long   383.57     111.0
208 2017-08-14     10225.28  10327.305000  Short  -144.09       3.0
209 2017-08-17     10369.37  10342.661667   Long   -48.04       1.0
210 2017-08-18     10321.33  10346.209000  Short   -70.74       4.0
211 2017-08-22     10392.07  10355.805500   Long    57.61      31.0
212 2017-09-22     10449.68  10467.725667  Short   -19.67      11.0
213 2017-10-03     10469.35  10466.183333   Long    91.09      58.0
214 2017-11-30     10560.44  10642.939833  Short   -90.67       4.0
215 2017-12-04     10651.11  10645.691667   Long   -84.26       1.0
216 2017-12-05     10566.85  10644.973333  Short  -143.88      28.0
217 2018-01-02     10710.73  10652.217833   Long  -306.73      35.0
218 2018-02-06     10404.00  10760.598167  Short  -390.55      17.0
219 2018-02-23     10794.55  10746.154500   Long   -96.38       7.0
220 2018-03-02     10698.17  10745.645667  Short   -86.17       4.0
221 2018-03-06     10784.34  10748.199833   Long   -39.02       1.0
222 2018-03-07     10745.32  10750.615667  Short   -77.92       1.0
223 2018-03-08     10823.24  10753.484500   Long     0.09      15.0
224 2018-03-23     10823.33  10850.817000  Short  -163.46       4.0
225 2018-03-27     10986.79  10864.706167   Long  -121.13       1.0
226 2018-03-28     10865.66  10870.179333  Short   -40.56       2.0
227 2018-03-30     10906.22  10883.641667   Long   -17.95       3.0
228 2018-04-02     10888.27  10896.199167  Short   -38.91       8.0
229 2018-04-10     10927.18  10904.317167   Long  -116.73       7.0
230 2018-04-17     10810.45  10908.809500  Short  -160.77       2.0
231 2018-04-19     10971.22  10910.894333   Long  -191.84       1.0
232 2018-04-20     10779.38  10907.945500  Short   -79.60      21.0
233 2018-05-11     10858.98  10790.707333   Long   -37.81      19.0
234 2018-05-30     10821.17  10845.742167  Short   -53.79       1.0
235 2018-05-31     10874.96  10849.609833   Long   -88.50      25.0
236 2018-06-25     10786.46  10877.453000  Short   -78.08      18.0
237 2018-07-13     10864.54  10836.650333   Long   -47.09       3.0
238 2018-07-16     10817.45  10834.087500  Short   -25.01       2.0
239 2018-07-18     10842.46  10836.503167   Long    -7.08       1.0
240 2018-07-19     10835.38  10840.767833  Short   -96.73       1.0
241 2018-07-20     10932.11  10846.970167   Long  -183.19      24.0
242 2018-08-13     10748.92  10923.618167  Short  -153.29      14.0
243 2018-08-27     10902.21  10898.927167   Long   -55.22      11.0
244 2018-09-07     10846.99  10877.227333  Short   -21.15       7.0
245 2018-09-14     10868.14  10861.170500   Long   -39.53       3.0
246 2018-09-17     10828.61  10861.873000  Short  -143.80       4.0
247 2018-09-21     10972.41  10869.988167   Long  -108.47      12.0
248 2018-10-03     10863.94  10901.919167  Short  1104.54     100.0
249 2019-01-11      9759.40   9747.392167   Long   -51.18       3.0
250 2019-01-14      9708.22   9743.874833  Short   -97.82       1.0
251 2019-01-15      9806.04   9741.070833   Long   752.25     118.0
252 2019-05-13     10558.29  10606.456833  Short  -217.05      37.0
253 2019-06-19     10775.34  10673.798167   Long  -122.79       7.0
254 2019-06-26     10652.55  10689.978000  Short  -121.35       1.0
255 2019-06-27     10773.90  10692.192333   Long  -224.86      36.0
256 2019-08-02     10549.04  10658.478333  Short  -207.89      34.0
257 2019-09-05     10756.93  10668.346167   Long   664.81     147.0
258 2020-01-30     11421.74  11758.973500  Short  -352.45      13.0
259 2020-02-12     11774.19  11773.005333   Long   -10.68       5.0
260 2020-02-17     11763.51  11788.930500  Short   991.29      72.0
261 2020-04-29     10772.22  10658.096500   Long  1492.16     148.0
262 2020-09-24     12264.38  12577.934833  Short  -439.85      12.0
263 2020-10-06     12704.23  12617.537000   Long   -41.32      23.0
264 2020-10-29     12662.91  12740.815333  Short   -73.10       5.0
265 2020-11-03     12736.01  12731.614333   Long  3166.36     190.0
266 2021-05-12     15902.37  16556.091333  Short  -693.30      13.0
267 2021-05-25     16595.67  16538.322833   Long   539.55      64.0
268 2021-07-28     17135.22  17152.970833  Short  -267.59       1.0
269 2021-07-29     17402.81  17162.293667   Long  -175.63      13.0
270 2021-08-11     17227.18  17330.563333  Short  -169.34      19.0
271 2021-08-30     17396.52  17367.713500   Long   -76.76       3.0
272 2021-09-02     17319.76  17387.008500  Short  -197.16       1.0
273 2021-09-03     17516.92  17392.970167   Long  -246.43       5.0
274 2021-09-08     17270.49  17398.003333  Short  -204.08       2.0
275 2021-09-10     17474.57  17399.165833   Long  -120.57       5.0
276 2021-09-15     17354.00  17411.832000  Short   279.45      42.0
277 2021-10-27     17074.55  17049.148167   Long   -87.14       2.0
278 2021-10-29     16987.41  17032.014833  Short   -80.83       3.0
279 2021-11-01     17068.24  17022.754000   Long   632.88      85.0
280 2022-01-25     17701.12  17846.808833  Short  -199.18      13.0
281 2022-02-07     17900.30  17869.918333   Long    68.99      15.0
282 2022-02-22     17969.29  17983.988833  Short   -86.44       1.0
283 2022-02-23     18055.73  17987.945833   Long  -461.18       1.0
284 2022-02-24     17594.55  17984.462667  Short  2177.20     172.0
285 2022-08-15     15417.35  15310.005333   Long  -172.21       7.0
286 2022-08-22     15245.14  15251.298333  Short    45.10       3.0
287 2022-08-25     15200.04  15172.492333   Long  -273.85       4.0
288 2022-08-29     14926.19  15123.260667  Short  -169.25       2.0
289 2022-08-31     15095.44  15071.022000   Long  -293.58       1.0

In [48]:


def set_single_max(index):
    last_signal_date = signal_df.loc[index -1 , "trade_date"]
    curr_signal_date = signal_df.loc[index , "trade_date"]
    
    max_period_price = df.loc[
        (df["trade_date"] >= last_signal_date) &
        (df["trade_date"] <= curr_signal_date),
        "close_price"
    ].max()
    min_period_price = df.loc[
            (df["trade_date"] >= last_signal_date) &
            (df["trade_date"] <= curr_signal_date),
        "close_price"
    ].min()
    
    max_period_profit = max_period_price - signal_df.loc[index-1,"close_price"]
    min_period_profit = min_period_price - signal_df.loc[index-1,"close_price"] 
    
    
    signal_df.loc[index-1, "max_period_price"] = max_period_price
    signal_df.loc[index-1, "min_period_price"] = min_period_price
    
    signal_df.loc[index-1, "max_period_profit"] = max_period_profit
    signal_df.loc[index-1, "min_period_profit"] = min_period_profit
    

for index in range(1, len(signal_df)):
    set_single_max(index)

In [49]:
signal_df

,trade_date,close_price,sma60,signal,profit,hold_day,max_period_price,min_period_price,max_period_profit,min_period_profit
0,2000-03-13,8811.95,9190.846500,Short,-721.92,10.0,9533.87,8536.05,721.92,-275.90
1,2000-03-23,9533.87,9330.423000,Long,-159.26,22.0,10186.17,9374.61,652.30,-159.26
2,2000-04-14,9374.61,9602.798500,Short,259.14,54.0,9374.61,8349.91,0.00,-1024.70
3,2000-06-07,9115.47,9088.918167,Long,-47.59,1.0,9115.47,9067.88,0.00,-47.59
4,2000-06-08,9067.88,9089.974833,Short,3691.76,215.0,9067.88,4614.63,0.00,-4453.25
5,2001-01-09,5376.12,5344.077000,Long,231.61,83.0,6104.24,5339.40,728.12,-36.72
6,2001-04-02,5607.73,5653.865167,Short,1527.22,217.0,5608.50,3446.26,0.77,-2161.47
7,2001-11-05,4080.51,4068.742000,Long,1787.32,178.0,6462.30,4080.51,2381.79,0.00
8,2002-05-02,5867.83,6049.507333,Short,1277.95,174.0,5910.69,3850.04,42.86,-2017.79
9,2002-10-23,4589.88,4538.422333,Long,-91.15,7.0,4601.37,4498.73,11.49,-91.15
10,2002-10-30,4498.73,4511.314333,Short,-80.41,1.0,4579.14,4498.73,80.41,0.00
11,2002-10-31,4579.14,4511.427500,Long,-78.59,1.0,4579.14,4500.55,0.00,-78.59
12,2002-11-01,4500.55,4507.757833,Short,-83.13,3.0,4583.68,4500.55,83.13,0.00
13,2002-11-04,4583.68,4505.815333,Long,-99.25,51.0,4823.67,4484.43,239.99,-99.25
14,2002-12-25,4484.43,4527.518833,Short,-82.94,1.0,4567.37,4484.43,82.94,0.00
15,2002-12-26,4567.37,4534.112333,Long,-109.62,4.0,4567.37,4457.75,0.00,-109.62
16,2002-12-30,4457.75,4548.467333,Short,-168.57,4.0,4626.32,4452.45,168.57,-5.30
17,2003-01-03,4626.32,4577.929167,Long,17.55,38.0,5078.80,4626.32,452.48,0.00
18,2003-02-10,4643.87,4730.782167,Short,34.55,65.0,4705.08,4260.45,61.21,-383.42
19,2003-04-16,4609.32,4591.349333,Long,-42.66,1.0,4609.32,4566.66,0.00,-42.66
20,2003-04-17,4566.66,4584.253333,Short,-91.64,1.0,4658.30,4566.66,91.64,0.00
21,2003-04-18,4658.30,4578.263333,Long,-102.20,4.0,4658.30,4556.10,0.00,-102.20
22,2003-04-22,4556.10,4567.482500,Short,-8.83,1.0,4564.93,4556.10,8.83,0.00
23,2003-04-23,4564.93,4561.047500,Long,-189.99,1.0,4564.93,4374.94,0.00,-189.99
24,2003-04-24,4374.94,4551.532000,Short,-90.63,32.0,4465.57,4139.50,90.63,-235.44
25,2003-05-26,4465.57,4400.141500,Long,1368.67,178.0,6142.32,4451.11,1676.75,-14.46
26,2003-11-20,5834.24,5847.082833,Short,-26.94,5.0,5861.18,5821.58,26.94,-12.66
27,2003-11-25,5861.18,5860.173500,Long,-0.57,1.0,5861.18,5860.61,0.00,-0.57
28,2003-11-26,5860.61,5862.987167,Short,-9.56,5.0,5870.17,5740.57,9.56,-120.04
29,2003-12-01,5870.17,5869.116333,Long,-23.02,7.0,5920.46,5847.15,50.29,-23.02
30,2003-12-08,5847.15,5888.260333,Short,-77.09,7.0,5924.24,5803.42,77.09,-43.73
31,2003-12-15,5924.24,5900.497833,Long,-37.01,1.0,5924.24,5887.23,0.00,-37.01
32,2003-12-16,5887.23,5904.022500,Short,-154.33,17.0,6041.56,5752.01,154.33,-135.22
33,2004-01-02,6041.56,5930.267167,Long,318.36,80.0,7034.10,6041.56,992.54,0.00
34,2004-03-22,6359.92,6422.920000,Short,-114.19,7.0,6474.11,6132.62,114.19,-227.30
35,2004-03-29,6474.11,6456.228167,Long,100.64,30.0,6880.18,6474.11,406.07,0.00
36,2004-04-28,6574.75,6645.792833,Short,951.89,114.0,6574.75,5316.87,0.00,-1257.88
37,2004-08-20,5622.86,5605.720667,Long,40.02,67.0,6103.00,5622.86,480.14,0.00
38,2004-10-26,5662.88,5742.637167,Short,-199.97,8.0,5862.85,5650.97,199.97,-11.91
39,2004-11-03,5862.85,5777.616500,Long,-24.43,19.0,6049.49,5838.42,186.64,-24.43
40,2004-11-22,5838.42,5878.207500,Short,-72.89,2.0,5911.31,5838.42,72.89,0.00
41,2004-11-24,5911.31,5881.136833,Long,-56.07,1.0,5911.31,5855.24,0.00,-56.07
42,2004-11-25,5855.24,5882.631833,Short,-38.03,8.0,5893.27,5778.65,38.03,-76.59
43,2004-12-03,5893.27,5883.090833,Long,-14.38,10.0,5925.28,5878.89,32.01,-14.38
44,2004-12-13,5878.89,5885.461167,Short,-30.76,1.0,5909.65,5878.89,30.76,0.00
45,2004-12-14,5909.65,5886.982167,Long,-30.57,29.0,6143.12,5879.08,233.47,-30.57
46,2005-01-12,5879.08,5911.896000,Short,-66.19,5.0,5945.27,5853.94,66.19,-25.14
47,2005-01-17,5945.27,5917.370667,Long,-49.92,2.0,5945.27,5895.35,0.00,-49.92
48,2005-01-19,5895.35,5925.955167,Short,-98.88,12.0,5994.23,5771.48,98.88,-123.87
49,2005-01-31,5994.23,5933.187000,Long,38.24,45.0,6259.69,5981.54,265.46,-12.69
50,2005-03-17,6032.47,6035.415167,Short,-11.48,1.0,6043.95,6032.47,11.48,0.00
51,2005-03-18,6043.95,6036.104667,Long,-25.16,4.0,6058.96,6018.79,15.01,-25.16
52,2005-03-22,6018.79,6036.924667,Short,-47.12,3.0,6065.91,6001.00,47.12,-17.79
53,2005-03-25,6065.91,6038.776167,Long,-104.67,4.0,6065.91,5961.24,0.00,-104.67
54,2005-03-29,5961.24,6038.657667,Short,-30.31,59.0,6028.75,5693.01,67.51,-268.23
55,2005-05-27,5991.55,5965.754333,Long,253.58,80.0,6455.57,5971.62,464.02,-19.93
56,2005-08-15,6245.13,6246.156167,Short,169.87,88.0,6245.13,5632.97,0.00,-612.16
57,2005-11-11,6075.26,5990.631833,Long,399.43,104.0,6742.39,6020.94,667.13,-54.32
58,2006-02-23,6474.69,6489.860000,Short,-63.53,1.0,6538.22,6474.69,63.53,0.00
59,2006-02-24,6538.22,6496.965500,Long,-44.07,11.0,6642.96,6494.15,104.74,-44.07
60,2006-03-07,6494.15,6536.261833,Short,-119.82,24.0,6613.97,6364.60,119.82,-129.55
61,2006-03-31,6613.97,6567.408167,Long,232.98,60.0,7474.05,6613.97,860.08,0.00
62,2006-05-30,6846.95,6852.802667,Short,-25.89,2.0,6872.84,6846.95,25.89,0.00
63,2006-06-01,6872.84,6857.753667,Long,-157.57,4.0,6959.64,6715.27,86.80,-157.57
64,2006-06-05,6715.27,6869.773500,Short,103.37,70.0,6734.51,6257.80,19.24,-457.47
65,2006-08-14,6611.90,6563.958667,Long,-105.98,7.0,6733.46,6505.92,121.56,-105.98
66,2006-08-21,6505.92,6545.155500,Short,-84.28,1.0,6590.20,6505.92,84.28,0.00
67,2006-08-22,6590.20,6540.344167,Long,-145.44,6.0,6590.20,6444.76,0.00,-145.44
68,2006-08-28,6444.76,6518.398333,Short,-142.36,2.0,6587.12,6444.76,142.36,0.00
69,2006-08-30,6587.12,6513.798667,Long,1091.55,183.0,7935.54,6587.12,1348.42,0.00
70,2007-03-01,7678.67,7727.322500,Short,-58.79,18.0,7737.46,7344.56,58.79,-334.11
71,2007-03-19,7737.46,7733.381333,Long,-1.26,1.0,7737.46,7736.20,0.00,-1.26
72,2007-03-20,7736.20,7737.644500,Short,-20.83,1.0,7757.03,7736.20,20.83,0.00
73,2007-03-21,7757.03,7741.281333,Long,836.01,147.0,9744.06,7757.03,1987.03,0.00
74,2007-08-15,8593.04,8884.331833,Short,-389.12,16.0,8982.16,8090.29,389.12,-502.75
75,2007-08-31,8982.16,8955.963333,Long,-59.18,4.0,8982.16,8922.98,0.00,-59.18
76,2007-09-04,8922.98,8977.019167,Short,-94.10,2.0,9017.08,8913.85,94.10,-9.13
77,2007-09-06,9017.08,8997.257167,Long,-79.50,4.0,9018.08,8937.58,1.00,-79.50
78,2007-09-10,8937.58,9012.778833,Short,-94.05,4.0,9031.63,8927.42,94.05,-10.16
79,2007-09-14,9031.63,9024.664167,Long,-131.72,3.0,9031.63,8899.91,0.00,-131.72
80,2007-09-17,8899.91,9024.009500,Short,-205.37,4.0,9105.28,8899.91,205.37,0.00
81,2007-09-21,9105.28,9030.874333,Long,-167.70,48.0,9809.88,8937.58,704.60,-167.70
82,2007-11-08,8937.58,9180.298500,Short,828.87,106.0,8970.92,7408.40,33.34,-1529.18
83,2008-02-22,8108.71,8106.111500,Long,-103.25,24.0,8658.64,8005.46,549.93,-103.25
84,2008-03-17,8005.46,8060.419333,Short,-173.89,2.0,8179.35,8005.46,173.89,0.00
85,2008-03-19,8179.35,8059.271667,Long,528.48,68.0,9295.20,8179.35,1115.85,0.00
86,2008-05-26,8707.83,8740.800333,Short,-70.56,1.0,8778.39,8707.83,70.56,0.00
87,2008-05-27,8778.39,8746.894167,Long,-112.66,1.0,8778.39,8665.73,0.00,-112.66
88,2008-05-28,8665.73,8753.608500,Short,3967.42,222.0,8745.35,4089.93,79.62,-4575.80
89,2009-01-05,4698.31,4596.765000,Long,-162.52,3.0,4789.84,4535.79,91.53,-162.52
90,2009-01-08,4535.79,4573.601333,Short,64.54,29.0,4535.79,4242.61,0.00,-293.18
91,2009-02-06,4471.25,4460.428833,Long,-34.31,14.0,4592.50,4436.94,121.25,-34.31
92,2009-02-20,4436.94,4457.967500,Short,-40.84,3.0,4477.78,4436.94,40.84,0.00
93,2009-02-23,4477.78,4464.431667,Long,-47.60,1.0,4477.78,4430.18,0.00,-47.60
94,2009-02-24,4430.18,4468.749667,Short,-63.56,1.0,4493.74,4430.18,63.56,0.00
95,2009-02-25,4493.74,4474.303000,Long,-67.91,5.0,4557.15,4425.83,63.41,-67.91
96,2009-03-02,4425.83,4482.794667,Short,-115.59,2.0,4541.42,4425.83,115.59,0.00
97,2009-03-04,4541.42,4482.758667,Long,1603.11,106.0,6954.10,4541.42,2412.68,0.00
98,2009-06-18,6144.53,6159.051833,Short,-86.62,1.0,6231.15,6144.53,86.62,0.00
99,2009-06-19,6231.15,6173.798000,Long,-33.68,4.0,6341.21,6197.47,110.06,-33.68
100,2009-06-23,6197.47,6203.155000,Short,-182.61,1.0,6380.08,6197.47,182.61,0.00
101,2009-06-24,6380.08,6222.722167,Long,274.72,58.0,7142.63,6380.08,762.55,0.00
102,2009-08-21,6654.80,6717.085500,Short,-183.45,3.0,6838.25,6654.80,183.45,0.00
103,2009-08-24,6838.25,6715.154667,Long,-147.50,3.0,6838.25,6690.75,0.00,-147.50
104,2009-08-27,6690.75,6708.339500,Short,-119.11,1.0,6809.86,6690.75,119.11,0.00
105,2009-08-28,6809.86,6709.052167,Long,681.05,91.0,7792.68,6809.86,982.82,0.00
106,2009-11-27,7490.91,7532.720500,Short,-91.30,3.0,7582.21,7490.91,91.30,0.00
107,2009-11-30,7582.21,7538.680833,Long,16.60,57.0,8356.89,7582.21,774.68,0.00
108,2010-01-26,7598.81,7863.860000,Short,-249.03,50.0,7847.84,7212.87,249.03,-385.94
109,2010-03-17,7847.84,7816.541000,Long,-35.97,6.0,7897.91,7811.87,50.07,-35.97
110,2010-03-23,7811.87,7822.825667,Short,-26.23,2.0,7838.10,7811.87,26.23,0.00
111,2010-03-25,7838.10,7823.118000,Long,-141.20,41.0,8171.94,7696.90,333.84,-141.20
112,2010-05-05,7696.90,7800.488167,Short,88.05,64.0,7772.13,7071.67,75.23,-625.23
113,2010-07-08,7608.85,7571.069833,Long,7.43,54.0,8034.49,7597.42,425.64,-11.43
114,2010-08-31,7616.28,7670.082500,Short,-104.54,2.0,7720.82,7616.28,104.54,0.00
115,2010-09-02,7720.82,7689.506000,Long,889.04,162.0,9145.35,7720.82,1424.53,0.00
116,2011-02-11,8609.86,8749.497833,Short,-233.98,7.0,8843.84,8609.86,233.98,0.00
117,2011-02-18,8843.84,8786.834167,Long,-170.17,4.0,8843.84,8673.67,0.00,-170.17
118,2011-02-22,8673.67,8800.698500,Short,-178.31,43.0,8851.98,8234.78,178.31,-438.89
119,2011-04-06,8851.98,8759.614500,Long,-119.39,6.0,8901.72,8732.59,49.74,-119.39
120,2011-04-12,8732.59,8752.411500,Short,-47.61,1.0,8780.20,8732.59,47.61,0.00
121,2011-04-13,8780.20,8750.694667,Long,-62.08,2.0,8802.73,8718.12,22.53,-62.08
122,2011-04-15,8718.12,8749.365500,Short,-95.16,5.0,8813.28,8638.55,95.16,-79.57
123,2011-04-20,8813.28,8737.605000,Long,-65.77,33.0,9049.25,8747.51,235.97,-65.77
124,2011-05-23,8747.51,8758.177500,Short,-40.89,3.0,8788.40,8727.09,40.89,-20.42
125,2011-05-26,8788.40,8768.208667,Long,-75.45,18.0,9062.35,8712.95,273.95,-75.45
126,2011-06-13,8712.95,8823.067667,Short,-81.29,43.0,8831.45,8478.86,118.50,-234.09
127,2011-07-26,8794.24,8782.007500,Long,-27.04,2.0,8817.49,8767.20,23.25,-27.04
128,2011-07-28,8767.20,8776.861833,Short,1231.38,90.0,8767.20,6877.12,0.00,-1890.08
129,2011-10-26,7535.82,7484.594167,Long,-227.14,15.0,7622.01,7308.68,86.19,-227.14
130,2011-11-10,7308.68,7420.889167,Short,-216.97,4.0,7525.65,7308.68,216.97,0.00
131,2011-11-14,7525.65,7413.159333,Long,-138.13,2.0,7525.65,7387.52,0.00,-138.13
132,2011-11-16,7387.52,7416.876500,Short,208.65,55.0,7387.81,6633.33,0.29,-754.19
133,2012-01-10,7178.87,7168.521500,Long,-75.25,6.0,7188.21,7103.62,9.34,-75.25
134,2012-01-16,7103.62,7157.479000,Short,-117.46,1.0,7221.08,7103.62,117.46,0.00
135,2012-01-17,7221.08,7152.976833,Long,418.74,79.0,8144.04,7221.08,922.96,0.00
136,2012-04-05,7639.82,7759.017333,Short,294.66,88.0,7788.27,6894.66,148.45,-745.16
137,2012-07-02,7345.16,7343.921167,Long,-35.20,7.0,7422.59,7309.96,77.43,-35.20
138,2012-07-09,7309.96,7319.885667,Short,39.47,22.0,7309.96,6970.69,0.00,-339.27
139,2012-07-31,7270.49,7197.322833,Long,181.23,72.0,7781.91,7217.51,511.42,-52.98
140,2012-10-11,7451.72,7453.891333,Short,-19.30,5.0,7471.02,7418.90,19.30,-32.82
141,2012-10-16,7471.02,7469.969000,Long,-6.62,1.0,7471.02,7464.40,0.00,-6.62
142,2012-10-17,7464.40,7477.230167,Short,34.20,41.0,7465.41,7088.49,1.01,-375.91
143,2012-11-27,7430.20,7425.024000,Long,367.83,113.0,8038.72,7430.20,608.52,0.00
144,2013-03-20,7798.03,7810.622167,Short,-58.09,5.0,7856.12,7796.22,58.09,-1.81
145,2013-03-25,7856.12,7819.150333,Long,-103.33,14.0,7942.35,7752.79,86.23,-103.33
146,2013-04-08,7752.79,7856.380500,Short,-105.19,3.0,7857.98,7728.54,105.19,-24.25
147,2013-04-11,7857.98,7855.001667,Long,-36.35,1.0,7857.98,7821.63,0.00,-36.35
148,2013-04-12,7821.63,7856.110667,Short,-109.17,7.0,7930.80,7763.53,109.17,-58.10
149,2013-04-19,7930.80,7859.123000,Long,20.86,55.0,8398.84,7930.80,468.04,0.00
150,2013-06-13,7951.66,8055.029500,Short,-227.88,28.0,8179.54,7663.23,227.88,-288.43
151,2013-07-11,8179.54,8088.694833,Long,-117.51,8.0,8260.11,8062.03,80.57,-117.51
152,2013-07-19,8062.03,8118.412500,Short,-152.62,4.0,8214.65,8062.03,152.62,0.00
153,2013-07-23,8214.65,8123.017333,Long,-130.15,6.0,8214.65,8084.50,0.00,-130.15
154,2013-07-29,8084.50,8126.462833,Short,-79.05,1.0,8163.55,8084.50,79.05,0.00
155,2013-07-30,8163.55,8126.371167,Long,-55.61,1.0,8163.55,8107.94,0.00,-55.61
156,2013-07-31,8107.94,8125.452500,Short,-30.69,5.0,8138.63,8056.22,30.69,-51.72
157,2013-08-05,8138.63,8116.477333,Long,-99.72,1.0,8138.63,8038.91,0.00,-99.72
158,2013-08-06,8038.91,8112.987167,Short,17.02,24.0,8038.91,7814.38,0.00,-224.53
159,2013-08-30,8021.89,8002.158833,Long,160.67,73.0,8465.06,8021.89,443.17,0.00
160,2013-11-11,8182.56,8210.336833,Short,-77.65,8.0,8260.21,8104.26,77.65,-78.30
161,2013-11-19,8260.21,8240.843667,Long,-55.75,1.0,8260.21,8204.46,0.00,-55.75
162,2013-11-20,8204.46,8246.001833,Short,-91.42,7.0,8295.88,8099.45,91.42,-105.01
163,2013-11-27,8295.88,8268.066000,Long,-31.40,70.0,8625.30,8264.48,329.42,-31.40
164,2014-02-05,8264.48,8402.984667,Short,-166.08,6.0,8430.56,8264.48,166.08,0.00
165,2014-02-11,8430.56,8410.708000,Long,710.88,175.0,9569.17,8430.56,1138.61,0.00
166,2014-08-05,9141.44,9250.864667,Short,-238.66,17.0,9380.10,9085.96,238.66,-55.48
167,2014-08-22,9380.10,9310.212333,Long,-22.49,19.0,9513.06,9357.61,132.96,-22.49
168,2014-09-10,9357.61,9364.458333,Short,278.74,71.0,9357.61,8512.88,0.00,-844.73
169,2014-11-20,9078.87,9029.075000,Long,-127.96,26.0,9225.11,8950.91,146.24,-127.96
170,2014-12-16,8950.91,8958.955333,Short,-48.61,3.0,8999.52,8828.36,48.61,-122.55
171,2014-12-19,8999.52,8950.814167,Long,611.31,146.0,9973.12,8999.52,973.60,0.00
172,2015-05-14,9610.83,9638.610167,Short,-105.94,5.0,9716.77,9579.48,105.94,-31.35
173,2015-05-19,9716.77,9649.126333,Long,-138.21,2.0,9716.77,9578.56,0.00,-138.21
174,2015-05-21,9578.56,9654.215333,Short,-90.85,5.0,9669.41,9578.56,90.85,0.00
175,2015-05-26,9669.41,9655.798000,Long,-43.72,6.0,9712.84,9625.69,43.43,-43.72
176,2015-06-01,9625.69,9660.501000,Short,1231.59,127.0,9625.69,7410.34,0.00,-2215.35
177,2015-10-06,8394.10,8357.239000,Long,-64.60,38.0,8857.02,8329.50,462.92,-64.60
178,2015-11-13,8329.50,8340.392667,Short,-89.92,4.0,8419.42,8295.40,89.92,-34.10
179,2015-11-17,8419.42,8351.445500,Long,-78.95,1.0,8419.42,8340.47,0.00,-78.95
180,2015-11-18,8340.47,8360.671333,Short,-136.73,1.0,8477.20,8340.47,136.73,0.00
181,2015-11-19,8477.20,8378.452333,Long,-77.06,5.0,8485.73,8400.14,8.53,-77.06
182,2015-11-24,8400.14,8414.044667,Short,-84.76,2.0,8484.90,8386.13,84.76,-14.01
183,2015-11-26,8484.90,8425.326833,Long,-86.50,1.0,8484.90,8398.40,0.00,-86.50
184,2015-11-27,8398.40,8431.674167,Short,-64.90,4.0,8463.30,8320.61,64.90,-77.79
185,2015-12-01,8463.30,8442.552000,Long,-7.24,2.0,8463.30,8456.06,0.00,-7.24
186,2015-12-03,8456.06,8457.990333,Short,243.99,75.0,8456.06,7664.01,0.00,-792.05
187,2016-02-16,8212.07,8154.395833,Long,261.80,72.0,8812.70,8212.07,600.63,0.00
188,2016-04-28,8473.87,8485.638000,Short,-62.00,32.0,8535.87,8053.69,62.00,-420.18
189,2016-05-30,8535.87,8499.787333,Long,-77.00,28.0,8716.25,8458.87,180.38,-77.00
190,2016-06-27,8458.87,8466.061333,Short,-46.64,1.0,8505.51,8458.87,46.64,0.00
191,2016-06-28,8505.51,8462.202500,Long,441.55,76.0,9262.89,8505.51,757.38,0.00
192,2016-09-12,8947.06,8964.526333,Short,-205.82,7.0,9152.88,8902.30,205.82,-44.76
193,2016-09-19,9152.88,8979.830167,Long,-13.84,44.0,9385.65,9139.04,232.77,-13.84
194,2016-11-02,9139.04,9172.555000,Short,-50.80,5.0,9189.84,9067.27,50.80,-71.77
195,2016-11-07,9189.84,9171.351667,Long,-246.64,2.0,9217.43,8943.20,27.59,-246.64
196,2016-11-09,8943.20,9168.491333,Short,-235.03,14.0,9178.23,8931.03,235.03,-12.17
197,2016-11-23,9178.23,9159.675500,Long,-26.12,1.0,9178.23,9152.11,0.00,-26.12
198,2016-11-24,9152.11,9160.015333,Short,-70.13,4.0,9222.24,9152.11,70.13,0.00
199,2016-11-28,9222.24,9162.691667,Long,-61.58,7.0,9263.53,9160.66,41.29,-61.58
200,2016-12-05,9160.66,9174.645667,Short,-90.11,1.0,9250.77,9160.66,90.11,0.00
201,2016-12-06,9250.77,9174.507333,Long,-46.51,15.0,9392.68,9204.26,141.91,-46.51
202,2016-12-21,9204.26,9210.701667,Short,-49.24,9.0,9253.50,9078.64,49.24,-125.62
203,2016-12-30,9253.50,9199.274333,Long,386.44,110.0,9972.49,9253.50,718.99,0.00
204,2017-04-19,9639.94,9704.357333,Short,-77.47,2.0,9717.41,9632.69,77.47,-7.25
205,2017-04-21,9717.41,9715.673000,Long,0.54,3.0,9717.95,9717.41,0.54,0.00
206,2017-04-24,9717.95,9721.730000,Short,-123.76,1.0,9841.71,9717.95,123.76,0.00
207,2017-04-25,9841.71,9730.059000,Long,383.57,111.0,10579.38,9841.71,737.67,0.00
208,2017-08-14,10225.28,10327.305000,Short,-144.09,3.0,10369.37,10225.28,144.09,0.00
209,2017-08-17,10369.37,10342.661667,Long,-48.04,1.0,10369.37,10321.33,0.00,-48.04
210,2017-08-18,10321.33,10346.209000,Short,-70.74,4.0,10392.07,10321.33,70.74,0.00
211,2017-08-22,10392.07,10355.805500,Long,57.61,31.0,10631.57,10392.07,239.50,0.00
212,2017-09-22,10449.68,10467.725667,Short,-19.67,11.0,10469.35,10257.02,19.67,-192.66
213,2017-10-03,10469.35,10466.183333,Long,91.09,58.0,10854.57,10469.35,385.22,0.00
214,2017-11-30,10560.44,10642.939833,Short,-90.67,4.0,10651.11,10560.44,90.67,0.00
215,2017-12-04,10651.11,10645.691667,Long,-84.26,1.0,10651.11,10566.85,0.00,-84.26
216,2017-12-05,10566.85,10644.973333,Short,-143.88,28.0,10710.73,10355.76,143.88,-211.09
217,2018-01-02,10710.73,10652.217833,Long,-306.73,35.0,11253.11,10404.00,542.38,-306.73
218,2018-02-06,10404.00,10760.598167,Short,-390.55,17.0,10794.55,10371.75,390.55,-32.25
219,2018-02-23,10794.55,10746.154500,Long,-96.38,7.0,10836.70,10698.17,42.15,-96.38
220,2018-03-02,10698.17,10745.645667,Short,-86.17,4.0,10784.34,10642.90,86.17,-55.27
221,2018-03-06,10784.34,10748.199833,Long,-39.02,1.0,10784.34,10745.32,0.00,-39.02
222,2018-03-07,10745.32,10750.615667,Short,-77.92,1.0,10823.24,10745.32,77.92,0.00
223,2018-03-08,10823.24,10753.484500,Long,0.09,15.0,11095.63,10823.24,272.39,0.00
224,2018-03-23,10823.33,10850.817000,Short,-163.46,4.0,10986.79,10823.33,163.46,0.00
225,2018-03-27,10986.79,10864.706167,Long,-121.13,1.0,10986.79,10865.66,0.00,-121.13
226,2018-03-28,10865.66,10870.179333,Short,-40.56,2.0,10906.22,10845.92,40.56,-19.74
227,2018-03-30,10906.22,10883.641667,Long,-17.95,3.0,10919.49,10888.27,13.27,-17.95
228,2018-04-02,10888.27,10896.199167,Short,-38.91,8.0,10927.18,10821.53,38.91,-66.74
229,2018-04-10,10927.18,10904.317167,Long,-116.73,7.0,10974.02,10810.45,46.84,-116.73
230,2018-04-17,10810.45,10908.809500,Short,-160.77,2.0,10971.22,10810.45,160.77,0.00
231,2018-04-19,10971.22,10910.894333,Long,-191.84,1.0,10971.22,10779.38,0.00,-191.84
232,2018-04-20,10779.38,10907.945500,Short,-79.60,21.0,10858.98,10488.58,79.60,-290.80
233,2018-05-11,10858.98,10790.707333,Long,-37.81,19.0,10987.77,10821.17,128.79,-37.81
234,2018-05-30,10821.17,10845.742167,Short,-53.79,1.0,10874.96,10821.17,53.79,0.00
235,2018-05-31,10874.96,10849.609833,Long,-88.50,25.0,11251.75,10786.46,376.79,-88.50
236,2018-06-25,10786.46,10877.453000,Short,-78.08,18.0,10864.54,10608.57,78.08,-177.89
237,2018-07-13,10864.54,10836.650333,Long,-47.09,3.0,10864.54,10817.45,0.00,-47.09
238,2018-07-16,10817.45,10834.087500,Short,-25.01,2.0,10842.46,10778.99,25.01,-38.46
239,2018-07-18,10842.46,10836.503167,Long,-7.08,1.0,10842.46,10835.38,0.00,-7.08
240,2018-07-19,10835.38,10840.767833,Short,-96.73,1.0,10932.11,10835.38,96.73,0.00
241,2018-07-20,10932.11,10846.970167,Long,-183.19,24.0,11098.13,10748.92,166.02,-183.19
242,2018-08-13,10748.92,10923.618167,Short,-153.29,14.0,10902.21,10683.90,153.29,-65.02
243,2018-08-27,10902.21,10898.927167,Long,-55.22,11.0,11099.57,10846.99,197.36,-55.22